"""
Rules Linter for Freelance Proposal Strategist.
Enforces the ABSOLUTE RULES specified in the prompt:
- Never start with freelancer's name or job title
- Never open with "I"
- Never list skills as bullet points
- Never use forbidden buzzwords: "passionate", "hardworking", "detail-oriented", "team player", "perfect fit", "excited about"
- Never claim "always deliver on time" or similar generic claims
- Never mention AI
- Never be sycophantic ("Great project!", "Love this idea!")
- Length limits by platform:
  * Upwork: 180-220 words
  * Direct Email: 220-300 words
  * LinkedIn: 100-150 words
  * Agency RFP: 250-350 words
"""

import re
from typing import List, Dict, Any
from proposal_agent.models import Platform

FORBIDDEN_BUZZWORDS = [
    "passionate",
    "hardworking",
    "detail-oriented",
    "team player",
    "perfect fit",
    "excited about",
    "i always deliver on time",
    "deliver on time and within budget",
    "i came across your job",
    "i am writing to apply",
    "my name is",
    "i am a senior",
    "i am an experienced",
    "great project",
    "love this idea",
    "amazing opportunity",
]

PLATFORM_LIMITS = {
    Platform.UPWORK: (180, 225),
    Platform.DIRECT_EMAIL: (220, 310),
    Platform.LINKEDIN: (100, 160),
    Platform.AGENCY_RFP: (250, 360),
    Platform.OTHER: (150, 300),
}

def count_words(text: str) -> int:
    """Count words in text excluding markdown headers and horizontal rules."""
    cleaned = re.sub(r"[#*_`~-]", " ", text)
    tokens = cleaned.strip().split()
    return len(tokens)

def lint_proposal(proposal_text: str, platform: Platform = Platform.UPWORK) -> List[str]:
    """Check proposal text against all absolute rules and return any violations."""
    violations: List[str] = []
    text_lower = proposal_text.strip().lower()
    first_paragraph = proposal_text.strip().split("\n\n")[0].strip() if proposal_text.strip() else ""

    # Rule 1: Never open with "I" or name/title
    if first_paragraph:
        cleaned_first = re.sub(r'^[#*_"\'\s]+', '', first_paragraph).strip()
        first_word = cleaned_first.split()[0].lower() if cleaned_first.split() else ""
        if first_word in ["i", "i'm", "i’ve", "i've", "my"]:
            violations.append("Violation: Proposal opens with 'I' or 'My'. Must open with client pain, sharp observation, or proof.")
        
        if any(cleaned_first.lower().startswith(p) for p in ["hi, my name is", "hello, my name is", "i am a", "my name is"]):
            violations.append("Violation: Proposal opens with freelancer introduction. State client's problem first.")

    # Rule 2: Never use forbidden buzzwords
    for word in FORBIDDEN_BUZZWORDS:
        if re.search(rf"\b{re.escape(word)}\b", text_lower):
            violations.append(f"Violation: Contains forbidden buzzword or cliché phrase: '{word}'.")

    # Rule 3: Never mention AI was used
    if any(p in text_lower for p in ["as an ai", "large language model", "generated by ai", "chatgpt"]):
        violations.append("Violation: Mentions AI or language model.")

    # Rule 4: Never list skills as bullet points
    # Look for bullet points with lists of technologies/skills
    lines = proposal_text.splitlines()
    bullet_count = 0
    for line in lines:
        line_stripped = line.strip()
        if line_stripped.startswith(("-", "*", "•")) and len(line_stripped.split()) < 6:
            bullet_count += 1
    if bullet_count >= 3:
        violations.append("Violation: Skills are listed as raw bullet points. Integrate tools naturally into approach.")

    # Rule 5: Word count validation
    min_words, max_words = PLATFORM_LIMITS.get(platform, (150, 300))
    wc = count_words(proposal_text)
    if wc < (min_words - 25):
        violations.append(f"Notice: Word count is {wc} words, which is below the recommended minimum of {min_words} for {platform.value}.")
    elif wc > (max_words + 25):
        violations.append(f"Notice: Word count is {wc} words, which exceeds target maximum of {max_words} for {platform.value}.")

    # Rule 6: Upwork specific - never mention "Upwork" inside
    if platform == Platform.UPWORK and "upwork" in text_lower:
        violations.append("Violation: Mentions 'Upwork' inside an Upwork proposal.")

    return violations

def sanitize_proposal(proposal_text: str) -> str:
    """Auto-fix small formatting issues like accidental 'I' openers."""
    cleaned = proposal_text.strip()
    # If it starts with "Hi, I am..." or "I came across...", clean it if possible
    cleaned = re.sub(r"^(Hi|Hello|Hey)\s*(there)?[,!.]?\s*", "", cleaned, flags=re.IGNORECASE)
    return cleaned.strip()
